### ISSUE TITLE
02.material-guide is literally gobbledygook to most creators.

### ISSUE THREAD

**Issue by MarcusLlewellyn** [highfidelity/hifi-docs-grav-content#221]
One of the largest hurdles I had as a creator in High Fidelity was figuring out the proper way to export material images to an FBX. The current documentation for this is at this github path:

hifi-docs-grav-content/02.create-and-explore/07.3d-modeling/01.materials/02.material-guide/docs.md

Information like, "Shininess = Hardness * 100 / 512" or "Opacity = 1 - average(Blender.Transparency.Alpha)" mean nothing at all to me. The documentation alludes to images of the Blender UI, which might clear things up, but these aren't actually present in the documentation.

What I need to know is simply which image maps correspond to which Blender Internal material settings. Instead, I see documentation better suited to someone writing an addon for Blender. Think creators and artists, not programmers.

**Comment by Mn8multimedia** [comment]
Yeah, I agree. There seems to be a lack of adequate documentation for High Fidelity for things like texturing,, NPC characters, etc.. It would be nice to see images of how to plugin the PBR textures into Maya, not using the discontinued Stingray.  I would also like to see if it was possible to prepare FBX PBR textures in Cinema 4d R19 which now has a PBR workflow, and would definately like to see more current video tutorials for High Fidelity.  Thanks!

**Comment by ingerjm0** [comment]
We have rewritten this page: https://docs.highfidelity.com/create/3d-models/pbr-materials-guide.html

If there are other things you'd like to see here, please let us know!
